In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('IMDB Dataset.csv')

In [3]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [4]:
df.head(100)

                                               review sentiment
0   One of the other reviewers has mentioned that ...  positive
1   A wonderful little production. <br /><br />The...  positive
2   I thought this was a wonderful way to spend ti...  positive
3   Basically there's a family where a little boy ...  negative
4   Petter Mattei's "Love in the Time of Money" is...  positive
..                                                ...       ...
95  Daniel Day-Lewis is the most versatile actor a...  positive
96  My guess would be this was originally going to...  negative
97  Well, I like to watch bad horror B-Movies, cau...  negative
98  This IS the worst movie I have ever seen, as w...  negative
99  I have been a Mario fan for as long as I can r...  positive

[100 rows x 2 columns]

In [5]:
df.shape

(50000, 2)

In [6]:
df['review'] = df['review'].str.lower()

In [7]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

# Remove html tag

In [8]:
# Remove html tag
import re
def remove_html_tags(text):
    return re.sub(r"<.*?>", " ", text)

In [9]:
text = "a wonderful little production. <br /><br />the.."

In [10]:
remove_html_tags(text)

'a wonderful little production.   the..'

In [11]:
df['review'] = df['review'].apply(remove_html_tags)

In [12]:
df['review'][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

In [13]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production.   the filming t...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

# remove URL

In [14]:
def remove_urls(text):
    return re.sub(r"https?://\S+|www\.\S+", " ", text)

In [19]:
text1 = "check my url https://www.yourube.com/subhasish"
text2 = "check my linkdin https://www.linkdin.com/Rahul"

In [20]:
remove_urls(text1)

'check my url  '

In [21]:
remove_urls(text2)

'check my linkdin  '

In [22]:
df['review'] = df['review'].apply(remove_urls)

In [24]:
df.sample(10)

                                                  review sentiment
24384  a very well directed version of eric bogosian'...  positive
42505  routine suspense yarn about a sociopath (dillo...  negative
22178  this is a film that in no way reflects the rea...  positive
1435   independent film that would make hollywood pro...  negative
538    sixth escapade for freddy krueger in which he ...  negative
28779  oh my. started out with such great potential -...  negative
5044   and a 30,000$ budget and this movie still look...  negative
46527  after a couple years of searching for the hump...  positive
14088  i really hoped for the best with this one, but...  negative
25333  my 10/10 rating of course applies only if you'...  positive

# Remove Punctuation

In [25]:
def remove_punctuation(text):
    return re.sub(r"[^\w\s]", "", text)

In [26]:
text = "Hello! Generative AI, is powerful. #AI @OpenAI"

In [27]:
remove_punctuation(text)

'Hello Generative AI is powerful AI OpenAI'

In [28]:
df['review'] = df['review'].apply(remove_punctuation)

In [30]:
df.sample(7)

                                                  review sentiment
32705  this movie is visually stunning who cares if s...  positive
37436  the movie is a real show of how unemotional an...  positive
36814  following is an intriguing thriller that requi...  positive
4273   scary movie 3 2003 was a bad idea to begin wit...  negative
32017  during the early 1980s kurt thomas was somethi...  negative
8594   since its release in 1983 a christmas story th...  negative
10302  it is a story of siberian village people from ...  positive

# chat_conversion handle

In [31]:
chat_words = {
    'AFAIK':'As Far As I Know',
    'AFK':'Away From Keyboard',
    'ASAP':'As Soon As Possible'
}


{
    "FYI": "For Your Information",
    "ASAP": "As Soon As Possible",
    "BRB": "Be Right Back",
    "BTW": "By The Way",
    "OMG": "Oh My God",
    "IMO": "In My Opinion",
    "LOL": "Laugh Out Loud",
    "TTYL": "Talk To You Later",
    "GTG": "Got To Go",
    "TTYT": "Talk To You Tomorrow",
    "IDK": "I Don't Know",
    "TMI": "Too Much Information",
    "IMHO": "In My Humble Opinion",
    "ICYMI": "In Case You Missed It",
    "AFAIK": "As Far As I Know",
    "BTW": "By The Way",
    "FAQ": "Frequently Asked Questions",
    "TGIF": "Thank God It's Friday",
    "FYA": "For Your Action",
    "ICYMI": "In Case You Missed It",
}

{'FYI': 'For Your Information',
 'ASAP': 'As Soon As Possible',
 'BRB': 'Be Right Back',
 'BTW': 'By The Way',
 'OMG': 'Oh My God',
 'IMO': 'In My Opinion',
 'LOL': 'Laugh Out Loud',
 'TTYL': 'Talk To You Later',
 'GTG': 'Got To Go',
 'TTYT': 'Talk To You Tomorrow',
 'IDK': "I Don't Know",
 'TMI': 'Too Much Information',
 'IMHO': 'In My Humble Opinion',
 'ICYMI': 'In Case You Missed It',
 'AFAIK': 'As Far As I Know',
 'FAQ': 'Frequently Asked Questions',
 'TGIF': "Thank God It's Friday",
 'FYA': 'For Your Action'}

In [32]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [33]:
chat_conversion('Do this work ASAP')

'Do this work As Soon As Possible'

# incorrect_text handling

pip install ftfy

### ftfy does not correct spelling mistakes. It mainly fixes broken Unicode/encoding text.

In [39]:
import ftfy

incorrect_text = "ceertaiin conditionas duriing seveal ggenerations aree moodified in the saame maner."

corrected_text = ftfy.fix_text(incorrect_text)

print(corrected_text)

ceertaiin conditionas duriing seveal ggenerations aree moodified in the saame maner.

In [44]:
from textblob import TextBlob
incorrect_text = 'ceertain conditionas duriing seveal ggenerations aree moodified in the saame maner.'

textBlb = TextBlob(incorrect_text)

textBlb.correct().string

'certain conditions during several generations are modified in the same manner.'

# stopwords

In [45]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\subha\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [46]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [48]:
len(stopwords.words('english'))

198

In [ ]:
def remove_stopwords(text):
    stop_words = set(stopwords.words("english"))
    return " ".join(
        word for word in text.split()
        if word.lower() not in stop_words
    )
df['review'].apply(remove_stopwords)

In [ ]:
df.head(7)